---
layout: preprint
#layout: review, 11pt
title: "my title"
author: 
  - name: Carl Boettiger
    affiliation: cstar
    email: cboettig(at)gmail.com
    footnote: Corresponding author
  - name: First Coauthor 
    affiliation: shortcode

address: 
  - code: cstar
    address: | 
      Center for Stock Assessment Research,
      110 Shaffer Rd,
      Santa Cruz, CA 95050, USA 
  - code: shortcode
    address: |
      Full address of First Coauthor

abstract: | 
          Write the abstract of the paper here




bibliography: components/references.bib
csl: components/ecology.csl
documentclass: components/elsarticle

output: 
  pdf_document:
    template: components/elsarticle.latex
    keep_tex: true
    fig_caption: true
---



```{r caching, include=FALSE}
library("methods")
library("knitr")
basename <- "manuscript"
opts_chunk$set(fig.path = paste("components/figure/", basename, "-", sep=""),
               cache.path = paste("components/cache/", basename, "/", sep=""))
opts_chunk$set(cache = 2)
opts_chunk$set(tidy=FALSE, warning=FALSE, message=FALSE, 
               comment = NA, verbose = TRUE, echo=FALSE)

# PDF-based figures
opts_chunk$set(dev='pdf')
```

```{r libraries, include=FALSE, cache = FALSE}
library("template")  # package should load itself, for packrat
library("rmarkdown")
library("knitcitations")
options(citation_format = "pandoc")
```




A citation to @Xie2013


A dynamic citation to `r citet("10.1098/rspb.2013.1372")`.  


# References

```{r include=FALSE, echo=FALSE, results="hide"}
citet(citation("knitr")) # a citation that wasn't added dyanmically above
write.bibtex(file="components/references.bib")
```

